### PR TITLE
Bump regex version

### PR DESCRIPTION
**Pull request by ParadoxSpiral**

### CODE REVIEW

**Comment by neoeinstein** [comment]
@quodlibetor Ping on this PR, as the stable version of Regex is now better able to take advantage of SIMD.

**Comment by quodlibetor** [comment]
Thanks! I'll get this released ASAP, probably as version 0.2

**Comment by quodlibetor** [comment]
@djzin this needs a release, after chrono-tz has been released. I've got a PR up that can be merged once chrono-tz has been released. If you feel like it you can `cargo owner --add github:chronotope:release-manager` and I'll be able to do this in the future.

**Comment by djzin** [comment]
I'm away for a couple of days, but I should be able to do that for you at the beginning of next week. Probably time for a tz library update, too
null

**Comment by quodlibetor** [comment]
Yup they're both ready for update. Thanks @djzin!

**Pull request merged**
