### PR TITLE
Update regex crate.

### LINKED ISSUE #1: Upgrade to regex 0.2
This is a minor comment, I'm trying to optimise my dependencies on a large project, and parse-zoneinfo depends on an old version of the regex crate, which itself depends on several older crates.

It would be great if parse-zoneinfo were upgraded to regex 0.2.

### PR DESCRIPTION
**Pull request by clarfonthey**
The only change is that I had to add `as_str` everywhere. Fixes #1.

### CODE REVIEW

**Comment by clarfonthey** [comment]
@lifthrasiir I think you'd be the person to merge this? I'd like to avoid multiple copies of the same dependencies for a project.

**Comment by clarfonthey** [comment]
@quodlibetor maybe you can merge?

**Comment by quodlibetor** [comment]
Apologies @clarcharr! I was fleeing a hurricane and am now traveling internationally sans-computer computer so I haven't had a lot of time for this.

I'm not 100% clear on what the semver-implications are for bumping a library whose types appear as private Fields inside a public struct. I think that is fine as a patch bump? It should be source compatible but might not be abi compatible, although I'm not sure how big a deal that is.

I'll merge this, but I won't have access to a computer that can push to crates.io until the end of September. In the mean time, if you have any guidance about how this version should be bumped I'm interested in finding out.

Thanks!

**Comment by clarfonthey** [comment]
@quodlibetor Fleeing a hurricane is definitely a reason to take a while; I hope that you and everyone with you is safe. :)

This is totally fine as a patch bump, as it wouldn't be breaking and would also avoid a bump in chrono-tz as well.

**Comment by quodlibetor** [comment]
As I mentioned in my attempted version bump, I can't actually release anything in the chronotope organization, so hopefully someone else will.

**Pull request merged**
