### PR TITLE
Support more-modern tz by supporting overflowing the month on >= and <=

### PR DESCRIPTION
**Pull request by quodlibetor**

### CODE REVIEW

**Comment by quodlibetor** [comment]
@djzin another slightly more meaningful change, once we merge and publish this (it's edited such that it's ready to cargo-publish as soon as it's merged) I can merge squash-merge chronotope/chrono-tz#37 and get us on an updated tz db.

**Comment by quodlibetor** [comment]
@djzin thanks for merging this, could you publish 0.3? the cargo.toml is ready to go.

**Comment by djzin** [comment]
That's done. I also published a new version of chrono-tz that uses version 0.3.
-------- Original message --------From: Brandon W Maister <notifications@github.com> Date: 10/06/2020  03:15  (GMT+00:00) To: chronotope/parse-zoneinfo <parse-zoneinfo@noreply.github.com> Cc: djzin <geoffrey@allott.email>, Mention <mention@noreply.github.com> Subject: Re: [chronotope/parse-zoneinfo] Support more-modern tz by supporting overflowing the month on >= and <= (#10) 
@djzin thanks for merging this, could you publish 0.3? the cargo.toml is ready to go.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chronotope/parse-zoneinfo/pull/10#issuecomment-641678124",
"url": "https://github.com/chronotope/parse-zoneinfo/pull/10#issuecomment-641678124",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by quodlibetor** [comment]
Great, thanks!

**Pull request merged**
